# Generated by Django 4.1.7 on 2023-02-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dete',
            new_name='date',
        ),
    ]
