# Generated by Django 4.1.7 on 2023-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='<django.db.models.fields.CharField>/')),
            ],
        ),
    ]
