# Generated by Django 4.1.7 on 2023-02-23 14:48

import CoreAPI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreAPI', '0002_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='userid',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CoreAPI.customusermodel'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(upload_to=CoreAPI.models.get_upload_path),
        ),
    ]
